sonar.projectKey=podinfo-emrah
sonar.projectName=podinfo-emrah
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.exclusions=**/*_test.go,**/bin/**,**/dist/**,**/testdata/**,**/vendor/**,charts/**,deploy/**,kustomize/**,timoni/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=cover.out

